package org.ucnj.paccess.dataaccess.beans;

import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Locale;

public class Order {

	// inner class for creating the activity date and time
	class ActivityDate {
		private int date, time;
		public ActivityDate() {
			Calendar cal = Calendar.getInstance();
			String year = Integer.toString(cal.get(Calendar.YEAR));
			String month = Integer.toString(cal.get(Calendar.MONTH) + 1);
			if (month.length() == 1) month = "0" + month;
			String day = Integer.toString(cal.get(Calendar.DAY_OF_MONTH));
			if (day.length() == 1) day = "0" + day;
			String hour = Integer.toString(cal.get(Calendar.HOUR_OF_DAY));
			if (hour.length() == 1) hour = "0" + hour;
			String minute = Integer.toString(cal.get(Calendar.MINUTE));
			if (minute.length() == 1) minute = "0" + minute;
			String second = Integer.toString(cal.get(Calendar.SECOND));
			if (second.length() == 1) second = "0" + second;
			date = Integer.parseInt(year + month + day);
			time = Integer.parseInt(hour + minute + second);
		}
		public int getDate() { return date; }
		public int getTime() { return time; }
	}
	
	public class Address {
		private String company = null;
		private String firstName = null;
		private String lastName = null;
		private String address1 = null;
		private String address2 = null;
		private String city = null;
		private String state = null;
		private String postCode = null;
		private String country = null;
	
		public String getCompany() { return company; }
		public String getFirstName() { return firstName; }
		public String getLastName() { return lastName; }
		public String getAddress1() { return address1; }
		public String getAddress2() { return address2; }
		public String getCity() { return city; }
		public String getState() {	return state; }
		public String getPostCode() { return postCode; }
		public String getCountry() { return country; }
		public void setCompany(String company) { this.company = company; }
		public void setFirstName(String firstName) { this.firstName = firstName; }
		public void setLastName(String lastName) { this.lastName = lastName; }
		public void setAddress1(String address1) { this.address1 = address1; }
		public void setAddress2(String address2) { this.address2 = address2; }
	 	public void setCity(String city) { this.city = city; }
		public void setState(String state) { this.state = state; }
		public void setPostCode(String postCode) { this.postCode = postCode; }
		public void setCountry(String country) { this.country = country; }
	}
	
	private final static char STATUS_PENDING  = '0';
	private final static char STATUS_ACCEPTED = '1';
	
	// generated by Union County
	private long invoiceNumber;
	private int orderDate;
	private int orderTime;
	private double amount;
	private char status;
	private int lastActitivityDate;
	private int lastActitivityTime;
	
	// generated by credit card processor
	private String txType = null;
	private String txId = null;
	private String txTimestamp = null;
	private String txApprovalCode = null;
	private String txResult = null;
	
	private Address shipTo = new Address();
	private Address billTo = new Address();
	
	private String email;
	private String phone;
	
	public Order() {
		super();
	}
	
	/**
	 * new order constructor
	 */
	public Order(double amount) {
		this.amount = amount;
		ActivityDate ad = new ActivityDate();
		orderDate = ad.getDate();
		orderTime = ad.getTime();
		lastActitivityDate = ad.getDate();
		lastActitivityTime = ad.getTime();
		status = STATUS_PENDING;
	}
	
	public void setPaymentDetails(
		String txType, String txId, String txTimestamp, String txApprovalCode, String txResult,
		String shipToCompany, String shipToFirstName, String shipToLastName,
		String shipToAddress1, String shipToAddress2, String shipToCity, 
		String shipToState, String shipToPostCode, String shipToCountry,
		String billToCompany, String billToFirstName, String billToLastName,
		String billToAddress1, String billToAddress2, String billToCity, 
		String billToState, String billToPostCode, String billToCountry,
		String email, String phone
	)
	{
		this.txType = txType;
		this.txId = txId;
		this.txTimestamp = txTimestamp;
		this.txApprovalCode = txApprovalCode;
		this.txResult = txResult;

		shipTo.setCompany(shipToCompany);
		shipTo.setFirstName(shipToFirstName);
		shipTo.setLastName(shipToLastName);
		shipTo.setAddress1(shipToAddress1);
		shipTo.setAddress2(shipToAddress2);
		shipTo.setCity(shipToCity);
		shipTo.setState(shipToState);
		shipTo.setPostCode(shipToPostCode);
		shipTo.setCountry(shipToCountry);

		billTo.setCompany(billToCompany);
		billTo.setFirstName(billToFirstName);
		billTo.setLastName(billToLastName);
		billTo.setAddress1(billToAddress1);
		billTo.setAddress2(billToAddress2);
		billTo.setCity(billToCity);
		billTo.setState(billToState);
		billTo.setPostCode(billToPostCode);
		billTo.setCountry(billToCountry);
		
		this.email = email;
		this.phone = phone;
		
		ActivityDate ad = new ActivityDate();
		lastActitivityDate = ad.getDate();
		lastActitivityTime = ad.getTime();
		status = STATUS_ACCEPTED;
	}

	public double getAmount() {
		return amount;
	}

	public String getAmountString() {
		NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.US);
		return nf.format(amount);
	}

	public long getInvoiceNumber() {
		return invoiceNumber;
	}

	public int getLastActitivityDate() {
		return lastActitivityDate;
	}

	public int getLastActitivityTime() {
		return lastActitivityTime;
	}

	public int getOrderDate() {
		return orderDate;
	}

	public int getOrderTime() {
		return orderTime;
	}

	public char getStatus() {
		return status;
	}

	public String getTxId() {
		return txId;
	}
	
	public String getTxType() {
		return txType;
	}  
	
	public String getTxApprovalCode() {
		return txApprovalCode;
	}
	
	public String getTxResult() {
		return txResult;
	}
	
	public String getTxTimestamp() {
		return txTimestamp;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public void setInvoiceNumber(long invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public void setLastActitivityDate(int lastActitivityDate) {
		this.lastActitivityDate = lastActitivityDate;
	}

	public void setLastActitivityTime(int lastActitivityTime) {
		this.lastActitivityTime = lastActitivityTime;
	}

	public void setOrderDate(int orderDate) {
		this.orderDate = orderDate;
	}

	public void setOrderTime(int orderTime) {
		this.orderTime = orderTime;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public void setTxId(String txId) {
		this.txId = txId;
	}
	
	public void setTxType(String txType) {
		this.txType = txType;
	}
	
	public void setTxTimestamp(String txTimestamp) {
		this.txTimestamp = txTimestamp;
	}
	
	public void setTxApprovalCode(String txApprovalCode) {
		this.txApprovalCode = txApprovalCode;
	}
	
	public void setTxResult(String txResult) {
		this.txResult = txResult;
	}

	public Address getShipTo() {
		return shipTo;
	}

	public void setShipTo(Address shipTo) {
		this.shipTo = shipTo;
	}

	public Address getBillTo() {
		return billTo;
	}

	public void setBillTo(Address billTo) {
		this.billTo = billTo;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
